export const ACTION_SCAN = 'ACTION_SCAN'
export const ACTION_DEVICES_FOUND = 'ACTION_DEVICES_FOUND'
export const ACTION_CLEAR = 'ACTION_CLEAR'
export const ACTION_DEVICE_INFO = 'ACTION_DEVICE_INFO'
export const ACTION_UPLOAD_SPT_DATA = 'ACTION_UPLOAD_SPT_DATA'
export const ACTION_UPDATE_TOKEN = 'ACTION_UPDATE_TOKEN'

export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS'
export const ACTION_LOGOUT = 'ACTION_LOGOUT'
